# Site
site_name: 为先百科
site_url: https://wx.lesnow.top

# Repository
repo_name: "LeSnow-Ye/wx-wiki"
repo_url: "https://github.com/LeSnow-Ye/wx-wiki"

# Contents
nav:
  - 简介:
      - Getting Started: index.md
      - 编辑规范: intro/edit-standard.md
      - Markdown 基础: intro/markdown.md
  - 课程:
      - 线性代数:
          - 线代期末复盘: courses/linear-algebra/final.md
  - TIC:
      - 海报: tic/posters.md

# Theme
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.path

# Plugins
plugins:
  - search
  - glightbox

# Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
