# Site
site_name: 为先百科
site_url: https://wx.lesnow.top

# Repository
repo_name: "LeSnow-Ye/wx-wiki"
repo_url: "https://github.com/LeSnow-Ye/wx-wiki"

# Contents
nav:
  - 简介:
      - 主页: index.md
      - 贡献方法: intro/contribute.md
      - 编辑规范: intro/edit-standard.md
      - Markdown 基础: intro/markdown.md
  - 资源:
      - 为先共享计划: resources/sharing-project.md
      - 实用网站: resources/links.md
      - 实用软件: resources/softwares.md
      # - 网站介绍:
      - 软件介绍:
          - Visual Studio Code: resources/softwares/vscode.md
  - 课程:
      - 微积分:
          - T1: courses/calculus/t1.md 
          - T2: courses/calculus/t2.md 
          - T3: courses/calculus/t3.md 
      - 基础物理:
          - 光学: courses/basic-physics/optics.md
          - 量子力学: courses/basic-physics/quantum-mechanics.md
      - 线性代数:
          - 线代期末复盘: courses/linear-algebra/final.md
  - TIC:
      - TIC2: tic/tic2.md
      #- 海报: tic/posters.md

# Theme
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    scheme: slate
    primary: teal
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.sections
    - content.code.copy

# Plugins
plugins:
  - search
  - glightbox

# Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
